### ISSUE TITLE
LSP not working on opened buffer

### ISSUE THREAD

**Issue by KiritchoukC** [olimorris/persisted.nvim#11]
Thanks for your work on this plugin, it's awesome.

I just have one issue when a session is restored.
On the opened focused buffer, LSP is not running.
I have to close the buffer and reopen it.
The other opened buffers are fine tho.

I don't know what could cause such behavior.

![persisted-issue](https://user-images.githubusercontent.com/29778468/166430330-b25507d1-bd85-4d51-a8b3-1aaf0df045f9.gif)

Any help is appreciated :)

**Comment by olimorris** [comment]
Really appreciate your comments, thank you.

A few questions:
* Are you using `autoload`? Could you share your persisted config?
* What about if you "force" reload the LSP like below?
```lua
:lua vim.lsp.stop_client(vim.lsp.get_active_clients())
:edit
```
* Is it definitely the LSP? I notice there's no highlighting which makes me wonder if it's a Treesitter issue?

**Comment by olimorris** [comment]
@KiritchoukC what's the best way to resolve this? I could put an `after_source` callback config option in? Or, I could just add the `:edit` command when autoloading?

**Comment by KiritchoukC** [comment]
If I'm the only one having this issue then the after_source callback is good enough imo. What do you think?

**Comment by olimorris** [comment]
@KiritchoukC I've just pushed an update using the `:edit` option. Can you let me know if it works?

**Comment by KiritchoukC** [comment]
@olimorris awsome man, I'll do that first thing tomorrow morning!

**Comment by KiritchoukC** [comment]
Unfortunately, I still have to type `:edit` when entering the buffer.
Don't spend too much time on this. I will find a workaround when I have time.
It's not that bad :)

**Comment by KiritchoukC** [comment]
Still not working.
I forked the repo and tried things but my knowledge in nvim plugin development is non-existent.
I'll continue investigating and will make a pr if by any chance I'm able to resolve it 😄

**Comment by KiritchoukC** [comment]
Update:
Still no success.
Last thing I tried is 
```lua
---Start recording a session and write to disk on a specific autocommand
---@return nil
function M.start()
  vim.api.nvim_create_augroup("Persisted", { clear = true })
  vim.api.nvim_create_autocmd(config.options.command, { command = "%s * lua require('persisted').save()", group = group })
  vim.api.nvim_create_autocmd("BufEnter", { command = "redraw | edit | echom 'Edited'", group = group })
  vim.g.persisting = true
end
```

Tried so many events, none of them would do the `:edit` for me
(SourcePost, BufEnter, TabEnter, WinEnter, FocusGained, FileReadPost, ...)

**Comment by olimorris** [comment]
I've added in the `after_source` callback. I've also included an example in the readme:

```lua
require("persisted").setup({
  after_source = function()
    -- Reload the LSP servers
    vim.lsp.stop_client(vim.lsp.get_active_clients())
    vim.cmd("edit")
  end
})
```

Let me know if this works.

**Comment by KiritchoukC** [comment]
Thank you for that.
No, it does not work. This does not make sense to me why manually `:edit` works but in function, it doesn't.

But the function is enough for me to try things so leave it like that and I will keep looking for a fix.

I appreciate your work, thank you @olimorris

**Comment by olimorris** [comment]
Haha damn!!! I'm refusing for us to beaten by this 😄.

Just to check, does stopping the LSPs first enable "edit" to work?

```lua
:lua vim.lsp.stop_client(vim.lsp.get_active_clients())
:edit
```

**Comment by KiritchoukC** [comment]
Yeah I actually took your example but no it does not work 🤷‍♂️

**Comment by askfiy** [comment]
You can try this:

```
vim.api.nvim_create_user_command("SessionLspLoad", function()
    vim.cmd("silent! SessionLoad")
    -- reload lsp servers
    vim.cmd("edit")
end, {})

-- after

mode = { "n" },
lhs = "<leader>sl",
rhs = "<cmd>SessionLspLoad<cr>",
options = { silent = true },
description = "Load session",

```

**Comment by olimorris** [comment]
@KiritchoukC wondered if you could test the latest version of the plugin. I think we may have solved this issue in #12

**Comment by KiritchoukC** [comment]
Awesome! I will try later and let you know how it went.
Thanks again

**Comment by KiritchoukC** [comment]
I can confirm that it is working with that latest version.
Thanks @olimorris and [@simonmclean](https://github.com/simonmclean)
